import { Platform, StatusBar, StyleSheet } from 'react-native';

export const colors = {
  background: '#0B0D12',
  surface: '#171A22',
  surfaceRaised: '#222633',
  line: '#343A4A',
  text: '#F5F7FB',
  muted: '#A5ADBD',
  accent: '#7C9CFF',
  accentSoft: '#26345F',
  success: '#48C78E',
  danger: '#FF6B7A',
} as const;

export const styles = StyleSheet.create({
  root: { backgroundColor: colors.background, flex: 1 },
  safe: { backgroundColor: colors.background, flex: 1 },
  safeTop: {
    paddingTop: Platform.OS === 'ios' ? 54 : (StatusBar.currentHeight ?? 0),
  },
  page: { flex: 1, paddingHorizontal: 18, paddingTop: 12 },
  header: { marginBottom: 12 },
  eyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  title: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  subtitle: { color: colors.muted, fontSize: 14, lineHeight: 20, marginTop: 4 },
  tabs: {
    backgroundColor: colors.surface,
    borderRadius: 14,
    flexDirection: 'row',
    gap: 4,
    marginBottom: 14,
    padding: 4,
  },
  tab: {
    alignItems: 'center',
    borderRadius: 10,
    flex: 1,
    minHeight: 42,
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  tabSelected: { backgroundColor: colors.accentSoft },
  tabText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  tabTextSelected: { color: colors.text },
  catalog: { paddingBottom: 32 },
  catalogCard: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    marginBottom: 10,
    padding: 16,
  },
  catalogTitle: { color: colors.text, fontSize: 17, fontWeight: '700' },
  catalogSummary: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  arrow: {
    color: colors.accent,
    fontSize: 20,
    position: 'absolute',
    right: 16,
    top: 22,
  },
  back: {
    alignSelf: 'flex-start',
    marginBottom: 8,
    minHeight: 36,
    justifyContent: 'center',
  },
  backText: { color: colors.accent, fontSize: 15, fontWeight: '700' },
  engineRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  pill: {
    borderColor: colors.line,
    borderRadius: 99,
    borderWidth: 1,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 14,
  },
  pillSelected: {
    backgroundColor: colors.accentSoft,
    borderColor: colors.accent,
  },
  pillText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  status: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    marginBottom: 10,
    padding: 10,
  },
  orderViewport: { maxHeight: 45, marginBottom: 2 },
  statusText: {
    color: colors.muted,
    fontFamily: 'Menlo',
    fontSize: 10,
    lineHeight: 15,
  },
  actions: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 10 },
  action: {
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.line,
    borderRadius: 9,
    borderWidth: 1,
    minHeight: 36,
    justifyContent: 'center',
    paddingHorizontal: 11,
  },
  actionDanger: { borderColor: colors.danger },
  actionText: { color: colors.text, fontSize: 11, fontWeight: '700' },
  canvas: { flex: 1 },
  list: { flex: 1 },
  row: {
    alignItems: 'center',
    backgroundColor: colors.surfaceRaised,
    borderBottomColor: colors.line,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
  },
  rowSelected: { backgroundColor: colors.accentSoft },
  rowText: { color: colors.text, fontSize: 14, fontWeight: '600' },
  grip: { color: colors.muted, fontSize: 18, letterSpacing: -3 },
  cards: { gap: 8 },
  card: {
    alignItems: 'center',
    backgroundColor: colors.surfaceRaised,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    height: 58,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  cardSelected: { borderColor: colors.accent, borderWidth: 2 },
  cardText: { color: colors.text, fontSize: 15, fontWeight: '700' },
  sectionHeader: {
    backgroundColor: '#12151D',
    height: 34,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  sectionHeaderText: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  sectionFooter: {
    backgroundColor: colors.surface,
    height: 26,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  sectionFooterText: { color: colors.muted, fontSize: 10 },
  dropLayout: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  accessibilityDropLayout: { marginTop: 10 },
  sourcePanel: { width: '100%' },
  sourceRow: { flexDirection: 'row', gap: 8 },
  draggable: { flex: 1, height: 62 },
  zone: {
    alignItems: 'center',
    borderColor: colors.success,
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 2,
    flex: 1,
    justifyContent: 'center',
    minHeight: 126,
  },
  zoneReject: { borderColor: colors.danger },
  zoneText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  instruction: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 10,
  },
  link: {
    color: colors.muted,
    fontFamily: 'Menlo',
    fontSize: 9,
    marginBottom: 8,
  },
});
